### ISSUE TITLE
Issues installing on Kepler?

### ISSUE THREAD

**Issue by diurnalist** [guari/eclipse-ui-theme#12]
I see that Kepler is supposedly supported, but when I click the Moonrise theme option in the dropdown, nothing happens. It seems to apply some of the styles, but everything else is largely unchanged. Restarting does nothing, either. I've also tried the Chrome Theme varietal.

Am I missing something?
![Eclipse Kepler - theme not applied](https://f.cloud.github.com/assets/796413/1537239/b5985258-4cc1-11e3-9a14-f02c6999645c.png)

**Comment by collinpeters** [comment]
I had a similar problem on Juno. I removed the plugin, and uninstalled the chrome theme plugin as well. Then restarted with the '-clean' option.  Then started from scratch and it started working. No idea what the problem was though.

**Comment by diurnalist** [comment]
Tried the '-clean' flag, to no avail. When you started from scratch, do you mean you created a new workspace? I didn't do that. Thanks for your help.

**Comment by mechanik0s** [comment]
a have this problem too

**Comment by guari** [comment]
In my experience, Eclipse has some issues with the dropins folder, I added a line in the Trouble-shooting paragraph into the README, as alternative, try also to install it with the update site.
As a side note, I saw that the Eclipse 4 Chrome Theme has some problems if you have installed the last ADT plugin.

**Comment by joshardt** [comment]
It didn't work for me. Neither the -clean flag nor the installation through the update worked. I am using Kepler on Mac OS X 10.9.

**Comment by guari** [comment]
Before releasing, I tested it on 10.7, it would be useful to known if it's a bug related to some new Cocoa changes added in Mavericks or a random Eclipse caching bug. If it's the first case, it might be related to this plugin and might be solved in some ways.
Can you try if the plugin is working as expected with a just downloaded standard Eclipse bundle and by using a new workspace?
(unfortunately, I have no Mac OS X 10.9 machine to test myself)

**Comment by joshardt** [comment]
I just downloaded a fresh new Eclipse and made a new workspace. Unfortunately it didn't help. Do you have an Apple store nearby? You can just go over there and test it on one of the macs they have.

**Comment by guari** [comment]
No Apple store nearby, but if we understand the problem, I should be able to fix it in some ways (provided it's not an Eclipse bug.. :) ).
Have you tried if the [previous version](https://github.com/guari/eclipse-ui-theme/blob/master/com.github.eclipseuitheme.themes.plugin/bin/com.github.eclipseuitheme.moonrise_0.8.3_OSX.jar?raw=true) for OSX was working? (this needs also Chrome Theme plugin to be installed)

**Comment by joshardt** [comment]
The previous version is working fine!

By the way, I don't have the Chrome Theme plugin installed. With the newest version I was trying to use MoonRise (Standalone) but neither the standalone nor the other MoonRise theme worked. With the previous MoonRise version you just gave me it works fine, even without the Chrome Theme plugin.

**Comment by guari** [comment]
Ok so it's probably a mistake in plugin.xml or into the CSS files for OSX, but curiously, they seem ok..
I'll take a better look at them this evening or tomorrow ;)
Do you have some errors/stacks printed in Console when trying to use the last version?

**Comment by joshardt** [comment]
Got no error messages, sorry.

**Comment by col-panic** [comment]
Performing eclipse -clean on OS X 10.8.5 i do not see the dark screen as shown above, but get the following error presented:

```
java.net.MalformedURLException
    at java.net.URL.<init>(URL.java:619)
    at java.net.URL.<init>(URL.java:482)
    at java.net.URL.<init>(URL.java:431)
    at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.parseStyleSheet(AbstractCSSEngine.java:199)
    at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:414)
    at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:375)
    at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.restore(ThemeEngine.java:537)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.initializeStyling(PartRenderingEngine.java:1239)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1000)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
Caused by: java.lang.NullPointerException
    at java.net.URL.<init>(URL.java:524)
    ... 28 more
```

It is a fresh Eclipse Kepler SR1

**Comment by MAAARKIN** [comment]
i have the same problem, anybody fixed this?

**Comment by matei** [comment]
Same here

**Comment by guari** [comment]
Unfortunately, it seems to be (again) an Eclipse bug, and (again) to fix it, it needs to keep the code dirty and redundant...
From some quick tests on OSX with Kepler, I noticed that:
- using some characters in file names can screw up the loading of the css file (eg: square brakets or underscore etc.);
- using multiple '@import' into CSS files can cause Eclipse to silently fail when loading the imported CSS;
- to keep things nonsense, the current version of the plugin works as expected with no errors on my OSX machine when running the project into a second Eclipse instance (right click on the project -> 'Run As..' -> 'Eclipse Application'), but silently fails when loaded as jar plugin (giving the error reported by @col-panic if launched with the terminal);
- every single test must be done with a fresh and clean Eclipse package and a new workspace because Eclipse stores somewhere into its cache the plugin and does not reload it if the content of the jar is changed.

In the meantime, you can use the previous version for OSX that should work ([moonrise_0.8.3_OSX.jar](https://github.com/guari/eclipse-ui-theme/blob/master/com.github.eclipseuitheme.themes.plugin/bin/com.github.eclipseuitheme.moonrise_0.8.3_OSX.jar?raw=true)).

**Comment by MAAARKIN** [comment]
i used this moonrise osx version on my macbook and the eclipse don't changed ;/, i will go to continue try fix this

**Comment by bryanwb** [comment]
I have this same issue as well :(

**Comment by danieldietrich** [comment]
me too (Mac/Mavericks + Kepler + BETA_JAVA8)

**Comment by guari** [comment]
For a quick fix you can delete the '@import url("...")' statement(s) into the CSS files and replace it by copy-pasting the whole content of the file that have to be imported.

I'll upload a fixed version next week, I need to figure out if the error is related to a plugin wrong configuration or to an Eclipse bug.

**Comment by danieldietrich** [comment]
thanks - the workaround works for me!

(I downloaded the 0.8.4 jar and replaced the @import lines in the css files...)

**Comment by adnang** [comment]
Hey I was just wondering if this issue has been fixed yet?

**Comment by MAAARKIN** [comment]
so, how i can replace the @import lines? I unjar, replace and jar again?

**Comment by adnang** [comment]
ah it's fine, i've got the previous version working without changing any of
the files. The only minor issue is the line number ruler is white.

**Comment by guari** [comment]
Waiting for a bug confirmation from Eclipse dev team.
Sorry if this issue it's taking so long, it's a very simple issue to solve but documentation on plugin development is lacking and I would like to avoid changing its whole structure at any minor update.
