### ISSUE TITLE
Unable to install from marketplace or url

### ISSUE THREAD

**Issue by JoeDailey** [guari/eclipse-ui-theme#69]
`https://raw.githubusercontent.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite/content.xml` responds with `Not Found`.

**Comment by DawidLoubser** [comment]
I have the same issue - unable to install (but in my case, due to not being able to find certain dependencies from the repos). I am running latest Eclipse Kepler.

**Comment by guari** [comment]
I can't reproduce this issue: I'm able to install the plugin on latest Kepler by using both Marketplace and direct update-site.
There is already `content.jar` archive that contains `content.xml` into the update-site root directory, so `content.xml` should be useless. 
PDE also builds the update-site with `content.jar`. In which cases is `content.xml` required instead of `content.jar`?

**Comment by JoeDailey** [comment]
I just pinged `https://raw.githubusercontent.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite/content.jar` and it was accessable like you said. I also tried to install via marketplace on eclipse kepler and it failed in the same fasion. Below I have attached an error log. 

I am not familiar with eclipse plugin deployment but from what I've gathered eclipse should be pointing
at `content.jar` instead of `context.xml`? If so maybe the owner of that package on the eclipse marketplace should check that to be sure.

As to why it is accessable to you and not me, DawidLoubser or others is puzzling.

``` error
eclipse.buildId=4.3.0.I20130605-2000
java.version=1.6.0_30
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

Error
Fri Jun 27 10:34:54 CDT 2014
Unable to read repository at https://raw.github.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite/content.xml.

javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
    at com.sun.net.ssl.internal.ssl.SSLSessionImpl.getPeerCertificates(Unknown Source)
    at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
    at org.apache.http.conn.ssl.SSLSocketFactory.createLayeredSocket(SSLSocketFactory.java:493)
    at org.apache.http.impl.conn.DefaultClientConnectionOperator.updateSecureConnection(DefaultClientConnectionOperator.java:232)
    at org.apache.http.impl.conn.ManagedClientConnectionImpl.layerProtocol(ManagedClientConnectionImpl.java:401)
    at org.apache.http.impl.client.DefaultRequestDirector.establishRoute(DefaultRequestDirector.java:840)
    at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:647)
    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
    at org.eclipse.ecf.provider.filetransfer.httpclient4.HttpClientFileSystemBrowser.runRequest(HttpClientFileSystemBrowser.java:263)
    at org.eclipse.ecf.provider.filetransfer.browse.AbstractFileSystemBrowser$DirectoryJob.run(AbstractFileSystemBrowser.java:69)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

**Comment by JoeDailey** [comment]
If you are also the owner on the eclipse marketplace also, I appologise for implying otherwise.

**Comment by guari** [comment]
Yes, both Marketplace and updatesite point to the same folder on github:
https://github.com/guari/eclipse-ui-theme/tree/master/com.github.eclipseuitheme.themes.updatesite
(no extra configurations are performed, Eclipse should look automatically at `content.jar`)

I tried again to download latest Kepler on Win7 (http://download.eclipse.org/eclipse/downloads/drops4/R-4.3.2-201402211700/index.php#EclipseSDK) but the plugin's updatesite works with no issues for me.

It might be an Eclipse caching issue, try to delete the `cache` directory `\eclipse\p2\org.eclipse.equinox.p2.repository\cache` and then refresh the repository:
go to `Preferences -> Install/Update -> Available Software Sites` => select the entry and click the `Reload` button on the right.

If that doesn't fix the issue, download this repo by using the `Download ZIP` button on the right side of the main webpage, then unzip it and try to load it in Eclipse from your hard-drive (`Help -> Install New Software...` => select `Add...` then click `Local...` and select the updatesite folder you downloaded `com.github.eclipseuitheme.themes.updatesite`), if it works then it's a network/firewall issue on your pc.

**Comment by LoLei** [comment]
[SOLVED] by installing a newer version of Eclipse.
I just tried your solution by downloading the Zip and manually adding it, but I get the same error:
Replace with Moonrise instead of Jeeeyul's

Cannot complete the install because one or more required items could not be found.
Software being installed: Jeeeyul's Themes 2.2.0.I20141028-103448 (net.jeeeyul.eclipse.themes.feature.feature.group 2.2.0.I20141028-103448)
Missing requirement: Jeeeyul's Eclipse Themes 2.2.0.I20141028-103448 (net.jeeeyul.eclipse.themes.ui 2.2.0.I20141028-103448) requires 'bundle org.eclipse.e4.ui.css.swt 0.0.0' but it could not be found
Cannot satisfy dependency:
From: Jeeeyul's Themes 2.2.0.I20141028-103448 (net.jeeeyul.eclipse.themes.feature.feature.group 2.2.0.I20141028-103448)
To: net.jeeeyul.eclipse.themes.ui [2.2.0.I20141028-103448]

**Comment by ducss2015** [comment]
I could not installed the plugin on Eclipse Luna Service Release 2 (4.4.2) over the market place. The error is as follows:

```
Unable to read repository at https://raw.github.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by trireme** [comment]
I have this problem in Neon.3
Unable to read repository at https://raw.github.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite/content.xml.
Warning: Server returned lastModified <= 0 for https://raw.github.com/guari/eclipse-ui-theme/master/com.github.eclipseuitheme.themes.updatesite/content.jar
