### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by suncore** [guari/eclipse-ui-theme#9]
HIi. I'm using the 0.8.2 moonrise theme (prebuilt package) together with the latest eclipse kepler. I'm getting a lot of exceptions:

java.lang.IllegalStateException
        at org.apache.batik.css.parser.CSSLexicalUnit.getFloatValue(Unknown Source)
        at org.eclipse.e4.ui.css.core.impl.dom.Measure.getFloatValue(Measure.java:38)
        at org.eclipse.e4.ui.css.swt.helpers.CSSSWTFontHelper.getFontData(CSSSWTFontHelper.java:153)
        at org.eclipse.e4.ui.css.swt.properties.converters.CSSValueSWTFontDataConverterImpl.convert(CSSValueSWTFontDataConverterImpl.java:72)
        at org.eclipse.e4.ui.css.swt.properties.converters.CSSValueSWTFontConverterImpl.convert(CSSValueSWTFontConverterImpl.java:33)
        at org.eclipse.e4.ui.css.core.impl.engine.AbstractCSSEngine.convert(AbstractCSSEngine.java:1125)
        at org.eclipse.e4.ui.css.swt.properties.css2.CSSPropertyFontSWTHandler$FontSelectionListener.applyStyles(CSSPropertyFontSWTHandler.java:298)
        at org.eclipse.e4.ui.css.swt.properties.css2.CSSPropertyFontSWTHandler$FontSelectionListener.styleSelected(CSSPropertyFontSWTHandler.java:340)
        at org.eclipse.e4.ui.css.swt.properties.css2.CSSPropertyFontSWTHandler$FontSelectionListener.handleEvent(CSSPropertyFontSWTHandler.java:369)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1392)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1416)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1401)
        at org.eclipse.swt.widgets.Control.gtk_expose_event(Control.java:3165)
        at org.eclipse.swt.widgets.Composite.gtk_expose_event(Composite.java:726)
        at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2090)
        at org.eclipse.swt.widgets.Control.windowProc(Control.java:5467)
        at org.eclipse.swt.widgets.Display.windowProc(Display.java:4569)
        at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
        at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:8742)
        at org.eclipse.swt.widgets.Display.eventProc(Display.java:1243)
        at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
        at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2288)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3361)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1113)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:997)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:138)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:610)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:567)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:636)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:591)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1450)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1426)

**Comment by suncore** [comment]
I just saw 0.8.3 is releaed. Problem is now fixed. :-) Many thanks for a great plugin!
-- Henrik
